<a href="https://colab.research.google.com/github/rajlm10/D2L-Torch/blob/main/D2L_looking_into_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 
from torch import nn


# Looking into the network

In [2]:
net=nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
X=torch.randn((2,4))
net(X)

tensor([[0.2962],
        [0.3001]], grad_fn=<AddmmBackward0>)

In [3]:
net.state_dict()

OrderedDict([('0.weight', tensor([[ 0.2325, -0.3744, -0.3166, -0.0389],
                      [ 0.1322, -0.4116,  0.0858, -0.1902],
                      [ 0.3968,  0.3834, -0.4747, -0.4488],
                      [ 0.4977,  0.0027,  0.2182,  0.1547],
                      [-0.2413, -0.3645, -0.4239, -0.0569],
                      [ 0.1880,  0.1750, -0.4226,  0.3092],
                      [-0.2907,  0.0057, -0.3280, -0.4070],
                      [-0.0546, -0.0281,  0.0794,  0.0119]])),
             ('0.bias',
              tensor([-0.3580, -0.4514, -0.2275,  0.1554,  0.0391, -0.4588, -0.1121, -0.2823])),
             ('2.weight',
              tensor([[-0.2201, -0.1809,  0.0803, -0.0132, -0.1396,  0.0477,  0.2607,  0.2682]])),
             ('2.bias', tensor([0.2864]))])

In [8]:
net.state_dict()['0.weight'],net.state_dict()['0.weight'].grad

(tensor([[ 0.2325, -0.3744, -0.3166, -0.0389],
         [ 0.1322, -0.4116,  0.0858, -0.1902],
         [ 0.3968,  0.3834, -0.4747, -0.4488],
         [ 0.4977,  0.0027,  0.2182,  0.1547],
         [-0.2413, -0.3645, -0.4239, -0.0569],
         [ 0.1880,  0.1750, -0.4226,  0.3092],
         [-0.2907,  0.0057, -0.3280, -0.4070],
         [-0.0546, -0.0281,  0.0794,  0.0119]]), None)

In [11]:
net[2].state_dict()['weight'].requires_grad

False

In [12]:
def block1():
  return nn.Sequential(nn.Linear(4, 8), nn.ReLU(),nn.Linear(8, 4), nn.ReLU())

def block2():
  net = nn.Sequential() 
  for i in range(4):
  # Nested here
    net.add_module(f'block {i}', block1()) 
  return net
rgnet = nn.Sequential(block2(), nn.Linear(4, 1)) 
rgnet(X)

tensor([[0.1099],
        [0.1099]], grad_fn=<AddmmBackward0>)

In [13]:
rgnet.state_dict()

OrderedDict([('0.block 0.0.weight',
              tensor([[ 0.3095, -0.4278,  0.2792,  0.2865],
                      [ 0.1315, -0.4395, -0.3540,  0.1121],
                      [ 0.3170, -0.1404, -0.4724,  0.0797],
                      [ 0.4650,  0.3947,  0.2618,  0.4645],
                      [-0.3625, -0.2194,  0.1755, -0.0928],
                      [-0.1427, -0.1425, -0.1731, -0.0334],
                      [-0.4787,  0.2730,  0.3682, -0.1145],
                      [ 0.0798, -0.4522,  0.3958,  0.4812]])),
             ('0.block 0.0.bias',
              tensor([-0.3687, -0.4589,  0.4744,  0.2302,  0.2669, -0.3121,  0.1756, -0.1354])),
             ('0.block 0.2.weight',
              tensor([[-0.0834, -0.2594, -0.0756, -0.0117,  0.2090, -0.3183, -0.3004, -0.0967],
                      [-0.3131, -0.3262,  0.0870, -0.2777,  0.1776,  0.2034, -0.0738, -0.2732],
                      [ 0.1142, -0.1988, -0.3177,  0.1647,  0.2563,  0.2981,  0.0535,  0.2462],
                      [ 0.

In [18]:
rgnet.state_dict()['0.block 0.2.weight']

tensor([[-0.0834, -0.2594, -0.0756, -0.0117,  0.2090, -0.3183, -0.3004, -0.0967],
        [-0.3131, -0.3262,  0.0870, -0.2777,  0.1776,  0.2034, -0.0738, -0.2732],
        [ 0.1142, -0.1988, -0.3177,  0.1647,  0.2563,  0.2981,  0.0535,  0.2462],
        [ 0.2341, -0.2195,  0.1245, -0.2714, -0.2339, -0.2550,  0.0587, -0.0932]])

In [14]:
rgnet

Sequential(
  (0): Sequential(
    (block 0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)

In [15]:
rgnet[0]

Sequential(
  (block 0): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
  (block 1): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
  (block 2): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
  (block 3): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
)

In [16]:
rgnet[0][1]

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=4, bias=True)
  (3): ReLU()
)

In [17]:
rgnet[0][1][2].weight

Parameter containing:
tensor([[-0.3088, -0.0686,  0.3389, -0.0499,  0.0944,  0.0364,  0.0269, -0.1468],
        [-0.1079,  0.0374, -0.3202, -0.3482, -0.2233,  0.0641,  0.1868,  0.3367],
        [ 0.1937, -0.1875,  0.0258,  0.2158, -0.0949, -0.3533,  0.2577, -0.1057],
        [ 0.1870, -0.0444,  0.0217,  0.2443,  0.2390, -0.0766, -0.0419, -0.3509]],
       requires_grad=True)

# Initialization for Linear Layers 

In [19]:
def init_normal(layer):
  if isinstance(layer,torch.nn.Linear):
    nn.init.normal_(layer.weight,mean=0,std=0.01)
    nn.init.zeros_(layer.bias)

net.apply(init_normal)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [21]:
def init_xavier(layer):
  if isinstance(layer,torch.nn.Linear):
    nn.init.xavier_uniform_(layer.weight)
    nn.init.zeros_(layer.bias)

net.apply(init_xavier)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

# Shared Parameters 

In [22]:
# We need to give the shared layer a name so that we can refer to its # parameters
shared = nn.Linear(8, 8)
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(),shared, nn.ReLU(), shared, nn.ReLU(), nn.Linear(8, 1))
net(X)

tensor([[-0.0975],
        [-0.0633]], grad_fn=<AddmmBackward0>)

In [23]:
# Check whether the parameters are the same
print(net[2].weight.data[0] == net[4].weight.data[0])
temp=net[2].weight.data[0, 0]
net[2].weight.data[0, 0] = 100
# Make sure that they are actually the same object rather than just having the # same value
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = temp #restore after checking


tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])


# Saving and loading tensors 

In [24]:
x = torch.arange(4) 
torch.save(x, 'x-file')
x2 = torch.load('x-file') 
x2

tensor([0, 1, 2, 3])

In [27]:
mydict = {'x': x, 'y': x.clone()} 
torch.save(mydict, 'mydict') 
mydict2 = torch.load('mydict') 
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0, 1, 2, 3])}

In [30]:
class MLP(nn.Module): 
  def __init__(self):
    super().__init__()
    self.hidden = nn.Linear(20, 256) 
    self.output = nn.Linear(256, 10)
  
  def forward(self, x):
    return self.output(nn.ReLU()(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20)) 
Y = net(X)

torch.save(net.state_dict(), 'mlp.params')

In [31]:
clone = MLP()  #We need to recreate the architecture since we only save weights
clone.load_state_dict(torch.load('mlp.params')) 
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [32]:
Y_clone = clone(X) 
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

# GPUs 101

In [33]:
!nvidia-smi

Thu Mar 10 05:24:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P8    35W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [34]:
torch.cuda.device_count()

1

In [35]:
def try_gpu(i=0):
  """Return gpu(i) if exists, otherwise return cpu().""" 
  if torch.cuda.device_count() >= i + 1:
    return torch.device(f'cuda:{i}') 
  return torch.device('cpu')

def try_all_gpus():
  """Return all available GPUs, or [cpu(),] if no GPU exists.""" 
  devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())] 
  return devices if devices else [torch.device('cpu')]
  
try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [48]:
%%time
z = torch.tensor([1, 2, 3]) #Default creation on CPU
print(z.device)

cpu
CPU times: user 232 µs, sys: 48 µs, total: 280 µs
Wall time: 206 µs


In [49]:
%%time
y = torch.tensor([1, 2],device=try_gpu())
print(y.device)

cuda:0
CPU times: user 361 µs, sys: 75 µs, total: 436 µs
Wall time: 443 µs


In [50]:
net = nn.Sequential(nn.Linear(3, 1)) 
net = net.to(device=try_gpu())

net[0].weight.data.device

device(type='cuda', index=0)

In [51]:
y=torch.rand((3,3))

net(y)

RuntimeError: ignored